apiVersion: v1
kind: Secret
metadata:
  name: jaspersoft-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "jaspersoft.name" . }}
    chart: {{ template "jaspersoft.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- include "evaluateSecret" (dict "secretKey" "dbUsername" "path" "db.databaseUserCredentials.username" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "dbPassword" "path" "db.databaseUserCredentials.password" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "jsMailSenderUN" "path" "mail.senderName" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "jsMailSenderPWD" "path" "mail.senderPassword" "values" .Values) }}

---
{{- if .Values.activeMQ.adminPassword  }}
apiVersion: v1
kind: Secret
metadata:
  name: activmq-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "jaspersoft.name" . }}
    chart: {{ template "jaspersoft.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- include "evaluateSecret" (dict "secretKey" "activemqPassword" "path" "activeMQ.adminPassword" "values" .Values) }}
 {{- end }}