apiVersion: v1
kind: Service
metadata:
  name: jaspersoft-service 
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "jaspersoft.name" . }}
    chart: {{ template "jaspersoft.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    description: "Jaspersoft SERVICE"
spec:
  selector:
    select: jsft-non-scheduler
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: jsft-port-8081
      port: 8081 
      protocol: TCP
      targetPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.activeMQ.isCluster }}
  name: activemq-broker-headless-service
{{- else }}
  name: activemq-broker-service
{{- end }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "jaspersoft.name" . }}
    chart: {{ template "jaspersoft.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    service: activemq-broker-svc
    select: activemq
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
{{- if .Values.activeMQ.isCluster }}
  clusterIP: None
{{- else }}
  type: ClusterIP
{{- end }}
  selector:
    select: activemq
  ports:
    - name: activemq-broker-port-61616
      port: 61616
      protocol: TCP
      targetPort: 61616
      
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-service
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "jaspersoft.name" . }}
    chart: {{ template "jaspersoft.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    service: activemq-svc
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    select: activemq
  ports:
    - name: activemq-port-8161
      port: 8161
      protocol: TCP
      targetPort: 8161



