version: "3.3"
services:
  db:
    deploy:
        # number of replicas service to be spawn
        replicas: 1
    # Entry point for your application
    entrypoint: ["/opt/devops-scripts/operations.sh"]
    # Input arguments for entry script
    command: ["INIT_MAINTENANCE|INSTALL_DB|INSTALL_ADDINS|INIT_INTEGRATIONS|SLEEP_INFINITY"]
    # Docker image
    image: itc-dsdc.ca.com:5000/clarity/dev/ppm_15.6.0.122.dev
    # List of environment variables required to run your application
    environment:
      - PPM_RESET_TENANT_DATA=true
      - PPM_SINGLE_TENANT_MODE=true
      - PPM_EXTERNAL_URL=
      - PPM_APP1_JVM_PARAMETERS=-Xms512m -Xmx2048m -XX:-UseGCOverheadLimit -DforceMemorySettings=false -XX:MaxMetaspaceSize=300m
      - PPM_APP1_TEST_MODE=false
      - PPM_APP1_PORT=8080
      - PPM_APP1_ENTRY_URL=https://app-route-8080-frppm-5.app.ppmosenew.10.131.142.50.nip.io
      - PPM_DB_VENDOR=oracle
      - PPM_DB_ORACLE_HOME=/opt/oracle
      - PPM_DB_BACKUP_DIR=/mnt/backups/15.6.0
      - PPM_DWH_BACKUP_DIRECTORY=/mnt/backups/15.6.0
      - PPM_DB_BACKUP_FILE=oracle_base.db
      - PPM_DB_HOST=lodippm02.ca.com
      - PPM_DB_PASSWORD=Niku#1234
      - PPM_DB_PORT=1521
      - PPM_DB_SCHEMA_NAME=niku_fr_03
      - PPM_DB_SERVICE_ID=niku
      - PPM_DB_SERVICE_NAME=niku
      - PPM_DB_PRIVILEGED_USER_PWD=system
      - PPM_DB_PRIVILEGED_USER=system
      - PPM_DB_USERNAME=niku_fr_03
      - PPM_DB_VENDOR=oracle
      - PPM_DWH_DB_HOST=lodippm02.ca.com
      - PPM_DWH_DB_PASSWORD=Niku#1234
      - PPM_DWH_DB_PORT=1521
      - PPM_DWH_BACKUP_FILE=dwh_oracle_base.db
      - PPM_DWH_DB_SCHEMA_NAME=ppm_dwh_fr_03
      - PPM_DWH_DB_SERVICE_ID=niku
      - PPM_DWH_DB_SERVICE_NAME=niku
      - PPM_DWH_DB_USERNAME=ppm_dwh_fr_03
      - PPM_DWH_DB_VENDOR=oracle
      - PPM_SYS_DB_SERVICE_NAME=clarity
      - PPM_SYS_DB_SERVICE_ID=clarity
      - PPM_SYS_DB_VENDOR=oracle
      - PPM_SYS_DB_HOST=lodippm02.ca.com
      - PPM_SYS_DB_PORT=1521
      - PPM_SYS_DB_USERNAME=JPing
      - PPM_SYS_DB_PASSWORD=JPing
      - PPM_USE_CUSTOM_DBLINK=true
      - PPM_SEARCHINDEX_DIR=/opt/ppm/files/searchindex
      - PPM_FILESTORE_DIR=/opt/ppm/files/filestore
      - JS_PRIVILEGED_USER=superuser
      - JS_PRIVILEGED_USER_PWD=superuser
      - PPM_JS_URL=http://jsft-node01-route-8081-frjsft.app.ppmosenew.10.131.142.50.nip.io/reportservice
      - PPM_RESET_JSFT_CONFIG=false
      - PPM_JS_ORG_ID=frorg
      - PPM_JS_ORG_NAME=frorg
      - PPM_HDP_INTEGRATION_ENABLE=true
      - HDP_DWH_RO_ROLE=ppm_dwh_fr_03_rorole
      - HDP_DWH_RO_USERNAME=ppm_dwh_fr_03_rouser
      - HDP_DWH_RO_USER_PASSWORD=Niku#1234
      - HDP_SERVER_URL=http://hdpapp-hdp01.app.ppm.dev.10.131.237.251.nip.io
      - HDP_USERNAME=frhdpuser3
      - HDP_PRIVILEGED_USER=d2cadmin
      - HDP_PRIVILEGED_USER_PWD=d2cadmin
      - HDP_DATASOURCENAME=frdatasource3
      - PPM_MAILSERVER_HOST=lodmail.ca.com
      - PPM_MAILSERVER_DEFAULTSENDERADRESS=test1@niku.com
      - PPM_MAILSERVER_SENDPROTOCOL=smtp
      - PPM_MAILSERVER_FETCHPROTOCOL=imap
      - PPM_MAILSERVER_USEAUTHENTICATION=true
      - PPM_MAILSERVER_USERNAME=
      - PPM_MAILSERVER_PASSWORD=
      - PPM_MAILSERVER_FROMADDRESS=
      - PPM_BG1_JVM_PARAMETERS=-Xms512m -Xmx2048m -XX:-UseGCOverheadLimit -DforceMemorySettings=false -XX:MaxMetaspaceSize=300m
      - PPM_CLIENT_PORT=9999
      - PPM_USE_JDBC_PING=true
      - PPM_ENCRYPT_PASSWORDS=false
      - PPM_FIPS_MODE_ENABLED=false
      - PPM_ENCRYPTION_SCHEME=AES
      - PPM_USE_SYSTEM_KEY=false
      - PPM_ENCRYPTION_FILE=
      - PPM_ADDINS=csk,apm
      - PPM_JS_CONTENT=csk
    labels:
      # List of properties which will help in deployment
      # Below 4 properties are used to establish the dependency between containers
      - com.ca.microservice.type=db # Type of the micro service
      - "com.ca.microservice.dependsOn=app" # List of services which are depend on this service
      - "com.ca.microservice.description=Database Interface" # Description of the service
      - name=db # Name of the service
      - service.deployment.strategy=recreate # Deployment strategy
      # Below properties are used to check readiness probe at specified time
      - service.healthcheck.readiness.interval=15m # execute for every 15 minutes
      - service.healthcheck.readiness.timeout=10s # Max Waiting time for the readiness probe result
      - service.healthcheck.readiness.retries=5 # number of retries in case of failure
      - service.healthcheck.readiness.period=30m # initial interval to wait to check probe
    healthcheck: # Used for liveness and readiness probe
      test: ["CMD", "", "/opt/devops-scripts/healthcheck/dbhealthcheck.sh"] # 1st input is liveness and 2nd input is for readiness probe
    volumes: # Retrieve data outside of container by claiming the volume. Please check volume definition in volumes section at the end of file
      - keystore-compose-claim:/opt/ppm/keystore # Claim the volume
  app:
    depends_on:
      - db
    ports:
      - "8080:8080"
    expose:
      - "8080"
    deploy:
          replicas: 1
    # replace username/repo:tag with your name and image details
    image: itc-dsdc.ca.com:5000/clarity/dev/ppm_15.6.0.122
    environment:
      - PPM_RESET_TENANT_DATA=false
      - PPM_SINGLE_TENANT_MODE=true
      - PPM_EXTERNAL_URL=
      - PPM_APP1_JVM_PARAMETERS=-Xms512m -Xmx2048m -XX:-UseGCOverheadLimit -DforceMemorySettings=false -XX:MaxMetaspaceSize=300m
      - PPM_APP1_TEST_MODE=false
      - PPM_APP1_PORT=8080
      - PPM_APP1_ENTRY_URL=https://app-route-8080-frppm-5.app.ppmosenew.10.131.142.50.nip.io
      - PPM_DB_VENDOR=oracle
      - PPM_DB_ORACLE_HOME=/opt/oracle
      - PPM_DB_BACKUP_DIR=/mnt/backups/15.6.0
      - PPM_DWH_BACKUP_DIRECTORY=/mnt/backups/15.6.0
      - PPM_DB_BACKUP_FILE=oracle_base.db
      - PPM_DB_HOST=lodippm02.ca.com
      - PPM_DB_PASSWORD=Niku#1234
      - PPM_DB_PORT=1521
      - PPM_DB_SCHEMA_NAME=niku_fr_03
      - PPM_DB_SERVICE_ID=niku
      - PPM_DB_SERVICE_NAME=niku
      - PPM_DB_PRIVILEGED_USER_PWD=system
      - PPM_DB_PRIVILEGED_USER=system
      - PPM_DB_USERNAME=niku_fr_03
      - PPM_DB_VENDOR=oracle
      - PPM_DWH_DB_HOST=lodippm02.ca.com
      - PPM_DWH_DB_PASSWORD=Niku#1234
      - PPM_DWH_DB_PORT=1521
      - PPM_DWH_BACKUP_FILE=dwh_oracle_base.db
      - PPM_DWH_DB_SCHEMA_NAME=ppm_dwh_fr_03
      - PPM_DWH_DB_SERVICE_ID=niku
      - PPM_DWH_DB_SERVICE_NAME=niku
      - PPM_DWH_DB_USERNAME=ppm_dwh_fr_03
      - PPM_DWH_DB_VENDOR=oracle
      - PPM_SYS_DB_SERVICE_NAME=clarity
      - PPM_SYS_DB_SERVICE_ID=clarity
      - PPM_SYS_DB_VENDOR=oracle
      - PPM_SYS_DB_HOST=lodippm02.ca.com
      - PPM_SYS_DB_PORT=1521
      - PPM_SYS_DB_USERNAME=JPing
      - PPM_SYS_DB_PASSWORD=JPing
      - PPM_USE_CUSTOM_DBLINK=true
      - PPM_SEARCHINDEX_DIR=/opt/ppm/files/searchindex
      - PPM_FILESTORE_DIR=/opt/ppm/files/filestore
      - JS_PRIVILEGED_USER=superuser
      - JS_PRIVILEGED_USER_PWD=superuser
      - PPM_JS_URL=http://jsft-node01-route-8081-frjsft.app.ppmosenew.10.131.142.50.nip.io/reportservice
      - PPM_RESET_JSFT_CONFIG=false
      - PPM_JS_ORG_ID=frorg
      - PPM_JS_ORG_NAME=frorg
      - PPM_HDP_INTEGRATION_ENABLE=true
      - HDP_DWH_RO_ROLE=ppm_dwh_fr_03_rorole
      - HDP_DWH_RO_USERNAME=ppm_dwh_fr_03_rouser
      - HDP_DWH_RO_USER_PASSWORD=Niku#1234
      - HDP_SERVER_URL=http://hdpapp-hdp01.app.ppm.dev.10.131.237.251.nip.io
      - HDP_USERNAME=frhdpuser3
      - HDP_PRIVILEGED_USER=d2cadmin
      - HDP_PRIVILEGED_USER_PWD=d2cadmin
      - HDP_DATASOURCENAME=frdatasource3
      - PPM_MAILSERVER_HOST=lodmail.ca.com
      - PPM_MAILSERVER_DEFAULTSENDERADRESS=test1@niku.com
      - PPM_MAILSERVER_SENDPROTOCOL=smtp
      - PPM_MAILSERVER_FETCHPROTOCOL=imap
      - PPM_MAILSERVER_USEAUTHENTICATION=true
      - PPM_MAILSERVER_USERNAME=
      - PPM_MAILSERVER_PASSWORD=
      - PPM_MAILSERVER_FROMADDRESS=
      - PPM_BG1_JVM_PARAMETERS=-Xms512m -Xmx2048m -XX:-UseGCOverheadLimit -DforceMemorySettings=false -XX:MaxMetaspaceSize=300m
      - PPM_CLIENT_PORT=9999
      - PPM_USE_JDBC_PING=true
      - PPM_ENCRYPT_PASSWORDS=false
      - PPM_FIPS_MODE_ENABLED=false
      - PPM_ENCRYPTION_SCHEME=AES
      - PPM_USE_SYSTEM_KEY=false
      - PPM_ENCRYPTION_FILE=
      - PPM_ADDINS=
      - PPM_JS_CONTENT=csk
    labels:
      - com.ca.microservice.type=app
      - com.ca.microservice.dependsOn=bg
      - "com.ca.microservice.description=app service"
      - name=app
      - config.update=true
      - service.healthcheck.period=1m45s
    healthcheck:
      test: ["CMD", "curl -f http://localhost:8080/niku/serverstatus/status?run=CLARITY_LOGIN", "curl -f http://localhost:8080/niku/serverstatus/status?run=CLARITY_LOGIN"]
      interval: 2m
      timeout: 30s
      retries: 2
    volumes:
      - keystore-compose-claim:/opt/ppm/keystore
  bg:
    depends_on:
      - app
    deploy:
          replicas: 1
    # replace username/repo:tag with your name and image details
    image: itc-dsdc.ca.com:5000/clarity/dev/ppm_15.6.0.122
    command: ["bg"]
    environment:
      - PPM_RESET_TENANT_DATA=false
      - PPM_SINGLE_TENANT_MODE=true
      - PPM_EXTERNAL_URL=
      - PPM_APP1_JVM_PARAMETERS=-Xms512m -Xmx2048m -XX:-UseGCOverheadLimit -DforceMemorySettings=false -XX:MaxMetaspaceSize=300m
      - PPM_APP1_TEST_MODE=false
      - PPM_APP1_PORT=8080
      - PPM_APP1_ENTRY_URL=http://localhost:8080
      - PPM_DB_VENDOR=oracle
      - PPM_DB_ORACLE_HOME=/opt/oracle
      - PPM_DB_BACKUP_DIR=/mnt/backups/15.6.0
      - PPM_DWH_BACKUP_DIRECTORY=/mnt/backups/15.6.0
      - PPM_DB_BACKUP_FILE=oracle_base.db
      - PPM_DB_HOST=lodippm02.ca.com
      - PPM_DB_PASSWORD=Niku#1234
      - PPM_DB_PORT=1521
      - PPM_DB_SCHEMA_NAME=niku_fr_03
      - PPM_DB_SERVICE_ID=niku
      - PPM_DB_SERVICE_NAME=niku
      - PPM_DB_PRIVILEGED_USER_PWD=system
      - PPM_DB_PRIVILEGED_USER=system
      - PPM_DB_USERNAME=niku_fr_03
      - PPM_DB_VENDOR=oracle
      - PPM_DWH_DB_HOST=lodippm02.ca.com
      - PPM_DWH_DB_PASSWORD=Niku#1234
      - PPM_DWH_DB_PORT=1521
      - PPM_DWH_BACKUP_FILE=dwh_oracle_base.db
      - PPM_DWH_DB_SCHEMA_NAME=ppm_dwh_fr_03
      - PPM_DWH_DB_SERVICE_ID=niku
      - PPM_DWH_DB_SERVICE_NAME=niku
      - PPM_DWH_DB_USERNAME=ppm_dwh_fr_03
      - PPM_DWH_DB_VENDOR=oracle
      - PPM_SYS_DB_SERVICE_NAME=clarity
      - PPM_SYS_DB_SERVICE_ID=clarity
      - PPM_SYS_DB_VENDOR=oracle
      - PPM_SYS_DB_HOST=lodippm02.ca.com
      - PPM_SYS_DB_PORT=1521
      - PPM_SYS_DB_USERNAME=JPing
      - PPM_SYS_DB_PASSWORD=JPing
      - PPM_USE_CUSTOM_DBLINK=true
      - PPM_SEARCHINDEX_DIR=/opt/ppm/files/searchindex
      - PPM_FILESTORE_DIR=/opt/ppm/files/filestore
      - JS_PRIVILEGED_USER=superuser
      - JS_PRIVILEGED_USER_PWD=superuser
      - PPM_JS_URL=http://jsft-node01-route-8081-frjsft.app.ppmosenew.10.131.142.50.nip.io/reportservice
      - PPM_RESET_JSFT_CONFIG=false
      - PPM_JS_ORG_ID=frorg
      - PPM_JS_ORG_NAME=frorg
      - PPM_HDP_INTEGRATION_ENABLE=true
      - HDP_DWH_RO_ROLE=ppm_dwh_fr_03_rorole
      - HDP_DWH_RO_USERNAME=ppm_dwh_fr_03_rouser
      - HDP_DWH_RO_USER_PASSWORD=Niku#1234
      - HDP_SERVER_URL=http://hdpapp-hdp01.app.ppm.dev.10.131.237.251.nip.io
      - HDP_USERNAME=frhdpuser3
      - HDP_PRIVILEGED_USER=d2cadmin
      - HDP_PRIVILEGED_USER_PWD=d2cadmin
      - HDP_DATASOURCENAME=frdatasource3
      - PPM_MAILSERVER_HOST=lodmail.ca.com
      - PPM_MAILSERVER_DEFAULTSENDERADRESS=test1@niku.com
      - PPM_MAILSERVER_SENDPROTOCOL=smtp
      - PPM_MAILSERVER_FETCHPROTOCOL=imap
      - PPM_MAILSERVER_USEAUTHENTICATION=true
      - PPM_MAILSERVER_USERNAME=
      - PPM_MAILSERVER_PASSWORD=
      - PPM_MAILSERVER_FROMADDRESS=
      - PPM_BG1_JVM_PARAMETERS=-Xms512m -Xmx2048m -XX:-UseGCOverheadLimit -DforceMemorySettings=false -XX:MaxMetaspaceSize=300m
      - PPM_CLIENT_PORT=9999
      - PPM_USE_JDBC_PING=true
      - PPM_ENCRYPT_PASSWORDS=false
      - PPM_FIPS_MODE_ENABLED=false
      - PPM_ENCRYPTION_SCHEME=AES
      - PPM_USE_SYSTEM_KEY=false
      - PPM_ENCRYPTION_FILE=
      - PPM_ADDINS=
      - PPM_JS_CONTENT=csk
    healthcheck:
      test: ["CMD", "/opt/devops-scripts/healthcheck/bghealthcheck.sh", "/opt/devops-scripts/healthcheck/bghealthcheck.sh"]
      interval: 5m
      timeout: 30s
      retries: 2
    labels:
      - com.ca.microservice.type=bg
      - com.ca.microservice.dependsOn=
      - "com.ca.microservice.description=bg service"
      - name=bg
      - service.healthcheck.period=1m
    volumes:
      - filestore-compose-claim:frppm-5:/opt/ppm/files
      - logstore-compose-claim:frppm-5:/opt/ppm/logs
volumes:
  keystore-compose-claim: # Define PVC claim for the PV
    external:
      frppmkeystore # PV for the nfs path
  filestore-compose-claim:
    external:
      frppmfilestore
  logstore-compose-claim:
    external:
      frppmlogs
