apiVersion: v1
kind: Secret
metadata:
  name: jaspersoft-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "jaspersoft.name" . }}
    chart: {{ template "jaspersoft.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  dbUsername: {{ .Values.db.databaseUserCredentials.username }}
  dbPassword: {{ .Values.db.databaseUserCredentials.password }}
  jsMailSenderUN: {{ .Values.mail.senderName }}
  jsMailSenderPWD: {{ .Values.mail.senderPassword }}

---
{{- if .Values.activeMQ.adminPassword  }}
apiVersion: v1
kind: Secret
metadata:
  name: activmq-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "jaspersoft.name" . }}
    chart: {{ template "jaspersoft.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  activemqPassword: {{ .Values.activeMQ.adminPassword }}
 {{- end }}