{{- if and (eq .Values.env "OP") (eq .Values.ingress.enabled true) -}}
apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  name: clarity-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: CLRTAFFINITYCOOKIE
spec:
  rules:
  - host: {{ .Values.namespace }}.clarity.{{ .Values.ingress.masterServerIP }}.nip.io
    http:
      paths:
      - path: 
        backend:
          serviceName: clarity-app-service
          servicePort: 8080
{{- end }}
---
{{- if and (eq .Values.env "OP") (eq .Values.ingress.enabled true) (eq .Values.xogDeployment.enable true) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: clarity-xog-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: CLRTXOGAFFINITYCOOKIE
    ingress.kubernetes.io/app-root: /niku/xog
spec:
  rules:
  - host: {{ .Values.namespace }}.xog.clarity.{{ .Values.ingress.masterServerIP }}.nip.io
    http:
      paths:
      - path: 
        backend:
          serviceName: clarity-xog-service
          servicePort: 8080
{{- end }}
---
{{- if and (eq .Values.env "OP") (eq .Values.ingress.enabled true) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: clarity-admin-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: CLRTAFFINITYCOOKIE
spec:
  rules:
    - host: {{ .Values.namespace }}.admin.clarity.{{ .Values.ingress.masterServerIP }}.nip.io
      http:
        paths:
          - path:
            backend:
              serviceName: clarity-admin-service
              servicePort: 8080
{{- end }}
