---
apiVersion: v1
kind: Secret
metadata:
  name: clarity-hdp-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  dwhReadOnlyUsername: {{ .Values.hdp.dwhReadOnlyUsername }}
  dwhReadOnlyUserPassword: {{ .Values.hdp.dwhReadOnlyUserPassword }}
  privilegedUser: {{ .Values.hdp.privilegedUser }}
  privilegedUserPassword: {{ .Values.hdp.privilegedUserPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: clarity-jaspersoft-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  privilegedUser: {{ .Values.jaspersoft.privilegedUser }}
  privilegedUserPassword: {{ .Values.jaspersoft.privilegedUserPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: clarity-dwh-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  userName: {{ .Values.dwh.userName }}
  password: {{ .Values.dwh.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: clarity-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  userName: {{ .Values.db.userName }}
  password: {{ .Values.db.password }}
  privilegedUser: {{ .Values.db.privilegedUser }}
  privilegedUserPassword: {{ .Values.db.privilegedUserPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: clarity-mailserver-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  userName: {{ .Values.mailserver.userName }}
  password: {{ .Values.mailserver.password }}
---
{{- if .Values.directoryserver }}
{{- if or .Values.directoryserver.adminUser .Values.directoryserver.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: clarity-directoryserver-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- with .Values.directoryserver }}
  {{- if .adminUser }}
  adminUser: {{ .adminUser }}
  {{- end }}
  {{- if .adminPassword }}
  adminPassword: {{ .adminPassword }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---

---
{{- if .Values.ssl }}
{{- if .Values.ssl.password }}
apiVersion: v1
kind: Secret
metadata:
  name: clarity-ssl-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.ssl.password }}
  {{- with .Values.ssl }}
  password: {{ .password }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---