#For K8S
{{- if eq .Values.platform "k8s" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clarity-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: CLRTPPMLB
    kubernetes.io/ingress.class: {{  .Values.ingress.app.class | default "clrt-ic-app" }}
    ingress.kubernetes.io/config-backend: |
      {{- range .Values.ingress.app.haproxyBackendConfig }}
      {{ . }}
      {{- end }}
    {{- range .Values.ingress.app.haproxyBackendAnnotations.clrtApp }}
    {{- range $key,$val := . }}
    ingress.kubernetes.io/{{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.namespace }}.{{ .Values.ingress.app.dnsName }}
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: clarity-app-service
              port:
                number: 8080
{{- end }}
---
{{- if eq .Values.platform "k8s" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clarity-xog-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: CLRTPPMXOGLB
    ingress.kubernetes.io/app-root: /niku/xog
    kubernetes.io/ingress.class: {{  .Values.ingress.app.class | default "clrt-ic-app" }}
    ingress.kubernetes.io/config-backend: |
      {{- range .Values.ingress.app.haproxyBackendConfig }}
      {{ . }}
      {{- end }}
    {{- range .Values.ingress.app.haproxyBackendAnnotations.clrtXog }}
    {{- range $key,$val := . }}
    ingress.kubernetes.io/{{ $key }}: {{ $val | quote }}
    {{- end}}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.namespace }}-xog.{{ .Values.ingress.app.dnsName }}
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: clarity-xog-service
              port:
                number: 8080
{{- end }}
---
{{- if eq .Values.platform "k8s" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clarity-admin-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: CLRTPPMADMLB
    kubernetes.io/ingress.class: {{ .Values.ingress.infra.class | default "clrt-ic-infra" }}
    ingress.kubernetes.io/config-backend: |
      {{- range .Values.ingress.infra.haproxyBackendConfig }}
      {{ . }}
      {{- end }}
    {{- range .Values.ingress.infra.haproxyBackendAnnotations.clrtAdmin }}
    {{- range $key,$val := . }}
    ingress.kubernetes.io/{{ $key }}: {{ $val | quote }}
    {{- end}}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.namespace }}-admin.{{ .Values.ingress.infra.dnsName }}
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: clarity-admin-service
              port:
                number: 8080
{{- end }}
---
#For GKE
{{- if eq .Values.platform "gke" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clarity-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    kubernetes.io/ingress.class: {{  .Values.ingress.app.class | default "clrt-ic-app" }}
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: CLRTPPMLB
    ingress.kubernetes.io/config-backend: |
      {{- range .Values.ingress.app.haproxyBackendConfig }}
      {{ . }}
      {{- end }}
    {{- range .Values.ingress.app.haproxyBackendAnnotations.clrtApp }}
    {{- range $key,$val := . }}
    ingress.kubernetes.io/{{ $key }}: {{ $val | quote }}
    {{- end}}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.namespace }}.{{ .Values.ingress.app.dnsName }}
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: clarity-app-service
              port:
                number: 8080
{{- end }}
---
{{- if eq .Values.platform "gke" }}
{{- if eq .Values.xogDeployment.enable true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clarity-xog-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    kubernetes.io/ingress.class: {{  .Values.ingress.app.class | default "clrt-ic-app" }}
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: CLRTPPMXOGLB
    ingress.kubernetes.io/app-root: /niku/xog
    ingress.kubernetes.io/config-backend: |
      {{- range .Values.ingress.app.haproxyBackendConfig }}
      {{ . }}
      {{- end }}
    {{- range .Values.ingress.app.haproxyBackendAnnotations.clrtXog }}
      {{- range $key,$val := . }}
    ingress.kubernetes.io/{{ $key }}: {{ $val | quote }}
      {{- end}}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.namespace }}-xog.{{ .Values.ingress.app.dnsName }}
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: clarity-xog-service
              port:
                number: 8080
{{- end }}
{{- end }}
---
{{- if eq .Values.platform "gke" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clarity-admin-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    kubernetes.io/ingress.class: {{ .Values.ingress.infra.class | default "clrt-ic-infra" }}
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: CLRTPPMADMLB
    ingress.kubernetes.io/config-backend: |
      {{- range .Values.ingress.infra.haproxyBackendConfig }}
      {{ . }}
      {{- end }}
    {{- range .Values.ingress.infra.haproxyBackendAnnotations.clrtAdmin }}
    {{- range $key,$val := . }}
    ingress.kubernetes.io/{{ $key }}: {{ $val | quote }}
    {{- end}}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.namespace }}-admin.{{ .Values.ingress.infra.dnsName }}
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: clarity-admin-service
              port:
                number: 8080
{{- end }}