kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-{{.Values.namespace}}
  namespace: {{.Values.namespace}}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["", "apps"]
  resources: ["configmaps","pods","pods/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
