---
apiVersion: v1
kind: Secret
metadata:
  name: clarity-hdp-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- include "evaluateSecret" (dict "secretKey" "dwhReadOnlyUsername" "path" "hdp.dwhReadOnlyUsername" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "dwhReadOnlyUserPassword" "path" "hdp.dwhReadOnlyUserPassword" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "privilegedUser" "path" "hdp.privilegedUser" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "privilegedUserPassword" "path" "hdp.privilegedUserPassword" "values" .Values) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: clarity-jaspersoft-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- include "evaluateSecret" (dict "secretKey" "privilegedUser" "path" "jaspersoft.privilegedUser" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "privilegedUserPassword" "path" "jaspersoft.privilegedUserPassword" "values" .Values) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: clarity-dwh-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- include "evaluateSecret" (dict "secretKey" "userName" "path" "dwh.userName" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "password" "path" "dwh.password" "values" .Values) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: clarity-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- include "evaluateSecret" (dict "secretKey" "userName" "path" "db.userName" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "password" "path" "db.password" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "privilegedUser" "path" "db.privilegedUser" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "privilegedUserPassword" "path" "db.privilegedUserPassword" "values" .Values) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: clarity-mailserver-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- include "evaluateSecret" (dict "secretKey" "userName" "path" "mailserver.userName" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "password" "path" "mailserver.password" "values" .Values) }}
---
{{- if .Values.directoryserver }}
{{- if or .Values.directoryserver.adminUser .Values.directoryserver.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: clarity-directoryserver-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- include "evaluateSecret" (dict "secretKey" "adminUser" "path" "directoryserver.adminUser" "values" .Values) }}
  {{- include "evaluateSecret" (dict "secretKey" "adminPassword" "path" "directoryserver.adminPassword" "values" .Values) }}
{{- end }}
{{- end }}
---
{{- if .Values.ssl }}
{{- if .Values.ssl.password }}
apiVersion: v1
kind: Secret
metadata:
  name: clarity-ssl-secret
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ template "clarity.name" . }}
    chart: {{ template "clarity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- include "evaluateSecret" (dict "secretKey" "password" "path" "ssl.password" "values" .Values) }}
{{- end }}
{{- end }}
---